[package]
name = "archipel-ipbeacon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.74"
bp7 = "0.10.5"
clap = "4.3.23"
dtn7 = "0.19.0"
log = "0.4.20"
serde = "1.0.183"
serde_cbor = "0.11.2"
socket2 = "0.5.3"

[[bin]]
name = "create-beacon"
path = "src/create-beacon.rs"

[[bin]]
name = "parse-beacon"
path = "src/parse-beacon.rs"

[[bin]]
name = "daemon"
path = "src/main.rs"